### ISSUE TITLE
Does lmdb-oql support multiple databases?

### ISSUE THREAD

**Issue by dskvr** [anywhichway/lmdb-oql#1]
`lmdb-js`, a core dependency of this module, supports multiple child databases in a single memory-mapped file. Does the nested-stack of your extensions support this core functionality? (extend, index, query, oql...) 

In short, Will a child database opened with `.openDB` be indexable by `lmdb-index` and by extension `lmdb-oql`? 

Great work btw. Been tinkering with this for a week and while it has some quirks, it's powerful, and fast! 

If I could nudge you to give more examples, particularly around operators, it would be particularly useful. Many of the operators do not behave as I would expect.

**Comment by anywhichway** [comment]
Yes, I updated the test suite in index.test.js to run over a parent and child. All tests pass.

```
const parent = withExtensions(open("test.db",{useVersions:true})),
    child = withExtensions(parent.openDB("child",{useVersions:true})),
    dbs = [parent,child];
for (let i=0;i<dbs.length;i++) {
    const db = dbs[i];
    ...
}
```

Could you open up separate issues for each of what you consider "quirks" so I can either document or eliminate?

With respect to the operators, could you open up a single issue with a couple of operators you don't understand. My guess is that addressing these will resolve your lack of understanding across the board.

Thanks for the compliment.

If you are satisfied with this response, please close issue.
